### ISSUE TITLE
TODO: Testing

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#177]
- [x] Fields change: Comment to Note
- [x] Fields change: Message to Comment
- [x] Activity comment
- [ ] Hooks/Webhooks
- [ ] Test thumbnail cache
- [ ] Test delete/update activity comments (https://github.com/directus/api/issues/153)
- [x] Permission: Explain -> Comment
- Activity Explain
  - [x] Test with explain `always`
  - [x] Test with explain `NULL`
  - [ ] Test with explain `update`
  - [ ] Test with explain `create`
  - [ ] Test with explain `none`

Schema & Data:
- [ ] Update sql dump
