### ISSUE TITLE
Improve filesystem

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#61]
I created this ticket to discuss all the different features/changes we want to implement to the new API.

Below are some of the discussion:

- [ ] Support configure multiple storage adapters (#170)
- [ ] Endpoint for Storage Adapters (#424)
- [ ] Easily add custom storage adapter (#170)
- [ ] Move base64 data content to file to reduce memory on big files
- [x] Add all the supported thumbnail sizes
- [x] Wrap all the urls/embed information into a new key
- [x] Replace file (#54)
- [x] Add full url key on local files
- [x] ~Validate file existing before creating it~
- [x] Fix embed files
- [x] Remove system thumbnails. Thumbnails are all going to be generated by the thumbnailer.
- [x] Fix thumbnailer
  - [x] Move settings from `config/api.php` to `directus_settings`
  - [x] Make the thumbnailer work on environment

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
